# Generated by Django 4.0.6 on 2022-07-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, null=True)),
                ('patient_identity_removed', models.BooleanField(null=True)),
                ('acquisition_date', models.DateField(null=True)),
                ('acquisition_date_time', models.DateTimeField(null=True)),
                ('exposure_time', models.IntegerField(null=True)),
                ('detector_temperature', models.FloatField(null=True)),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
    ]
